ALTER TABLE "events" RENAME COLUMN "action_id" TO "actor_id";--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "timestamp" timestamp DEFAULT now() NOT NULL;